JavaScript: Weather app
mahmoud717/Weather-app pull request #1
Opened 2020-12-23 21:28 UTC by mahmoud717

In this project, I built a Weather app with javascript and webpack. with the use of openweather API.

2020-12-23 21:49 UTC, whiz25 requested changes
## Changes Required 🙏🏿 
Amazing job on this PR. I like the design of the app. It looks awesome. I like how the search text field hides away nicely.
Let's fix one thing before merging this PR.
- [ ] add a toggle button to toggle temperature value between `F` and `C`

### Martin Afani

2020-12-24 10:03 UTC, mahmoud717 commented
To keep the UI clean, I added the event listener to the temperature itself.

2020-12-24 10:38 UTC, mosaaleb requested changes
#### Changes required

Well done @mahmoud717 :clap:. Thanks for implementing the changes required from the prevoius review. Yet, we have some requirements that aren't met yet. Kindly take a look at my comments below.


- [ ] We still need to add another script for building the project in **development**.

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/scripts_requirement.png)


Please handle this requirements and submit a new code review.

##### Muhammad Ebeid

2020-12-24 10:38 UTC, mosaaleb commented on src/app/utils/CallAPI.js
> +    handleError();
- [ ] **[OPTIONAL]** We can alternatively reject the promise here and use catch block in this function call (in `eventListeners.js`) to handle the error.
Ideally this function shouldn't have any side effects, it will either return a rejected or resloved promise. Any other logic should reside within the `then` `catch` `finally` blocks in the function call.

2020-12-24 10:38 UTC, mosaaleb commented on src/app/utils/eventListeners.js
> +      console.log(degree, temp.innerText);
- [ ] Do not use Window.alert() or Window.confirm().

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/alert_requirement.png)

2020-12-24 13:15 UTC, mahmoud717 commented
The webpack configuration I have lets you run the project as a dev server In the development. Or build a minified version in production.
Which is all you need.

There are no requirements to adding any other scripts in the curriculum, Odin, or TSE guidelines.

2020-12-24 15:05 UTC, Forison approved these changes
# Status::Approved✔️
#### Good job on addressing the issues raised earlier, I think your webpack config is ok. Kindly go ahead and merge the branch and proceed to the next milestone🤗.
#### Happy coding👨‍💻
Addo Forison

2020-12-25 11:00 UTC, merged